### ISSUE TITLE
Number of digits

### ISSUE THREAD

**Issue by 983** [Wilfred/the_end_times#2]
What was the number of digits used for the benchmark?
I could not find any big numbers in "run" and the default values for different languages seem to vary:

100
https://github.com/Wilfred/the_end_times/blob/master/programs/pidigits/Python3_CPython/pidigits.py#L12
512
https://github.com/Wilfred/the_end_times/blob/master/programs/pidigits/Rust_Rust/pidigits.rs#L88
1000
https://github.com/Wilfred/the_end_times/blob/master/programs/pidigits/CommonLisp_SBCL/pidigits.lisp#L7

**Comment by Wilfred** [comment]
Argh! Yikes! I think you're right and my comparison numbers are completely off. I'll try to fix this and the blog post soon.

**Comment by Wilfred** [comment]
OK, I've had some time to look at this. We are actually generating 10,000 digits in all languages.

Every language has a `run` script that passes the argument in, e.g. https://github.com/Wilfred/the_end_times/blob/master/programs/pidigits/Python3_CPython/run
